#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

. .builder

npm install

mkdir -p target/

if [ -d source/pub.favicon/ ]; then

  for entry in source/pub.favicon/*; do

    copy_entry "$entry" "target/pub/${entry#source/pub.favicon/}"
  done
fi

for dir in source/pub.lib.*/; do

  for entry in "${dir}"*; do

    copy_entry "$entry" "target/pub/lib/${entry#${dir}}"
  done
done

for dir in source/pub.*/; do
 
  dir="${dir%/}"
  
  name="${dir##*.}"

  dir2="${dir#source/}"
  dir2="${dir2%.*}"
  dir2="${dir2//.//}"
  
  if [ -f "$dir/$name.html" ]; then

    build_html "$dir/$name.html" "target/$dir2/$name.html"
    build_css "$dir/$name.css" "target/$dir2/$name.css"
    build_js "$dir/$name.js" "target/$dir2/$name.js"
  fi
done

echo -e "\nDone"
